# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.recruitEmployee = QtWidgets.QWidget()
        self.recruitEmployee.setObjectName("recruitEmployee")
        self.gridLayoutWidget = QtWidgets.QWidget(self.recruitEmployee)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 70, 561, 371))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.addName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.addName.setObjectName("addName")
        self.gridLayout.addWidget(self.addName, 0, 2, 1, 1)
        self.btnAddEmployee = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAddEmployee.setObjectName("btnAddEmployee")
        self.gridLayout.addWidget(self.btnAddEmployee, 3, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.jobBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.jobBox.setObjectName("jobBox")
        self.jobBox.addItem("")
        self.jobBox.addItem("")
        self.gridLayout.addWidget(self.jobBox, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.recruitEmployee, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"        \n"
"    background-color: rgb(57, 57, 57);\n"
"    color: rgb(68, 68, 68);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageQueries = QtWidgets.QWidget()
        self.pageQueries.setObjectName("pageQueries")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageQueries)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameQueries = QtWidgets.QFrame(self.pageQueries)
        self.frameQueries.setStyleSheet("QFrame{\n"
"        \n"
"    \n"
"    background-color: rgb(57, 57, 57);\n"
"}")
        self.frameQueries.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameQueries.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQueries.setObjectName("frameQueries")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameQueries)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameQueriesPages = QtWidgets.QFrame(self.frameQueries)
        self.frameQueriesPages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameQueriesPages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQueriesPages.setObjectName("frameQueriesPages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameQueriesPages)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnRecruit = QtWidgets.QPushButton(self.frameQueriesPages)
        self.btnRecruit.setObjectName("btnRecruit")
        self.verticalLayout_4.addWidget(self.btnRecruit)
        self.btnFire = QtWidgets.QPushButton(self.frameQueriesPages)
        self.btnFire.setObjectName("btnFire")
        self.verticalLayout_4.addWidget(self.btnFire)
        self.btnTransfer = QtWidgets.QPushButton(self.frameQueriesPages)
        self.btnTransfer.setObjectName("btnTransfer")
        self.verticalLayout_4.addWidget(self.btnTransfer)
        self.btnStartProject = QtWidgets.QPushButton(self.frameQueriesPages)
        self.btnStartProject.setObjectName("btnStartProject")
        self.verticalLayout_4.addWidget(self.btnStartProject)
        self.btnEndProject = QtWidgets.QPushButton(self.frameQueriesPages)
        self.btnEndProject.setObjectName("btnEndProject")
        self.verticalLayout_4.addWidget(self.btnEndProject)
        self.horizontalLayout.addWidget(self.frameQueriesPages)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frameQueries)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget_2)
        self.verticalLayout_2.addWidget(self.frameQueries)
        self.stackedWidget.addWidget(self.pageQueries)
        self.pageReports = QtWidgets.QWidget()
        self.pageReports.setObjectName("pageReports")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageReports)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameReports = QtWidgets.QFrame(self.pageReports)
        self.frameReports.setStyleSheet("Qframe {\n"
"            \n"
"    \n"
"    color: rgb(58, 58, 58);\n"
"\n"
"}")
        self.frameReports.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameReports.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameReports.setObjectName("frameReports")
        self.verticalLayout_3.addWidget(self.frameReports)
        self.stackedWidget.addWidget(self.pageReports)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddEmployee.setText(_translate("MainWindow", "add"))
        self.label.setText(_translate("MainWindow", "Employee name"))
        self.jobBox.setItemText(0, _translate("MainWindow", "developer"))
        self.jobBox.setItemText(1, _translate("MainWindow", "tester"))
        self.label_2.setText(_translate("MainWindow", "Select jop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recruitEmployee), _translate("MainWindow", "Tab 1"))
        self.btnRecruit.setText(_translate("MainWindow", "RECRUITING"))
        self.btnFire.setText(_translate("MainWindow", "FIRING"))
        self.btnTransfer.setText(_translate("MainWindow", "TRANFERING"))
        self.btnStartProject.setText(_translate("MainWindow", "ENDING PROJECT"))
        self.btnEndProject.setText(_translate("MainWindow", "STARTING PROJECT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
